### ISSUE TITLE
Synapse Struct member max_number_of_connections unused?

### ISSUE THREAD

**Issue by nasiryahm** [OFTNAI/Spike#14]
I am doing some initial documentation for the parent Synapses class (Synapses.h). There seems to be an unused parameter, can anyone confirm that it is unused on all branches? At least on nas_lin and dev_master it is unused.

In synapses_parameters_struct, int max_number_of_connections_per_pair.

@james-isbister @aeguchi, do you guys mind if I remove it?

**Comment by nasiryahm** [comment]
The line in question:
https://github.com/OFTNAI/Spike/blob/dev_master/Synapses/Synapses.h#L38

**Comment by aeguchi** [comment]
Hi Nas,

In my most recent push, I have implemented the function. It has not been
merged tho.

Aki

**Comment by nasiryahm** [comment]
Thanks Aki. I shall leave it in and place a sensible comment in there. *thumbs up*
