### ISSUE TITLE
build.sh file is missing

### ISSUE THREAD

**Issue by denisalevi** [OFTNAI/Spike#29]
Hey there!

fbe709fb2 deleted `Build/build.sh`. Guess that was not intended? Or [the documentation](https://sites.google.com/view/spike-simulator/home#h.p_fmWStCTtyvBd) needs an update. Checking out and running that deleted `build.sh` works fine to run the examples.

And I wasn't quite sure which `Spike` repo to use? @nasiryahm yours is linked in the documentation but seems to be a fork?

**Comment by nasiryahm** [comment]
Hi! Nice to see you in the issues :)

1afe3c1 adds `Build/build.sh` again. It was indeed unintended. I appreciate the nudge.

This is the official Spike repo so you should use this one. I use my own fork for development etc -- helps me manage my own developed master branch. If you want bleeding edge, feel free to use mines but everything in my fork will be merged here soon and I will make all links etc more consistent. Expect more details, documentation, and tests once my Thesis is done (eta 2 weeks).

Either way, keep the issues coming!
