### ISSUE TITLE
Wrong connectivity in Brunel10K sample

### ISSUE THREAD

**Issue by denniskb** [OFTNAI/Spike#30]
In your Brunel10K sample code you're creating the connections `P->E` and `P->I` twice by calling `connect_with_sparsity()` one-too-many times in each case. This results in an *observed* synapse count of

`#syn ~= 0.075 * #neurons^2`

, when the *expected* count is

`#syn ~= 0.05 * #neurons^2`

Please confirm, thank you!

**Comment by nasiryahm** [comment]
Hi Dennis,

Good catch, you are quite right the `P->N` connections are being created twice. This has slipped through from the iterating of the Brunel10K network for the [SNNSimulatorComparison](https://github.com/nasiryahm/SNNSimulatorComparison) repository. I'll get it corrected.

**Comment by nasiryahm** [comment]
36f79cfa7e3cf515578f888358c8fc3efb6ccd04
