### ISSUE TITLE
Wrong refractory period in Brunel sample

### ISSUE THREAD

**Issue by denniskb** [OFTNAI/Spike#32]
[Offending line](https://github.com/OFTNAI/Spike/blob/c26ec8d6d50b5dd2d1e896a7f5b89ece844ea5a2/Examples/Brunel10K.cpp#L124) reads

`... = 0.0f * pow(10, -3)` when it should read

`... = 2.0f * pow(10, -3)`.

**Comment by nasiryahm** [comment]
Hi Dennis,

Feel free to leave a pull request to fix this, or I can do it on a laptop soon. In general this Brunel file is more of an example of how to use the Spike simulator and if you are interested in the Brunel simulations, I would check out the [SNNSimulatorComparison](https://github.com/nasiryahm/SNNSimulatorComparison) repository version.

**Comment by denniskb** [comment]
Got it!, the issue was just meant as an FYI.

**Comment by nasiryahm** [comment]
Thank you in any case, I really appreciate people pointing out things that are missing or not easily understood. Not sure if that always comes across in my brief comments. Sorted :)
